version: 2.1
executors:
  docker-executor:
    docker:
      - image: cimg/node:7.10
        auth:
          # ensure you have first added these secrets
          # visit app.circleci.com/settings/project/github/sawthunaing/nodejs-mongodb-circleci/environment-variables
          username: $DOCKERHUB_USERNAME
          password: $DOCKERHUB_PWD
jobs:
  build-and-push-img:

    executor: docker-executor
    steps:
      - checkout
    
      - setup_remote_docker: # Set up Docker
        version: 20.10.7
        docker_layer_caching: true

      - run: 
        name: Build and push Docker image to DockerHub
        command: |
          # Set environment variables
          export IMAGETAG=gatone-$CIRCLE_BUILD_NUM  # You can use a different tag if desired

          # Build the Docker image
          docker build -t phogatone/nodejs:$IMAGETAG .

          # Authenticate with your Docker registry (e.g., Docker Hub)
          docker login -u "$DOCKERHUB_USERNAME" -p "$DOCKERHUB_PWD"

          # Push the Docker image to the registry
          docker push phogatone/nodejs:$IMAGETAG



workflows:
  nodejs-build-workflow:
    jobs:
      build-and-push-img :
  
