
version: 2.1

jobs:
  build:
    docker:
      - image: circleci/node:14

    steps:
      - checkout

        - setup_remote_docker: # Set up Docker
          version: "20.10.7"
          docker_layer_caching: "true"

      - run:
           name: Build and push Docker image to DockerHub
           command: |
            # Set environment variables
            export IMAGETAG=cptmarvel-$CIRCLE_BUILD_NUM  # You can use a different tag if desired

            # Build the Docker image
            docker build -t phogatone/nodejs:$IMAGETAG .

            # Authenticate with your Docker registry (e.g., Docker Hub)
            docker login -u "$DOCKERHUB_USERNAME" -p "$DOCKERHUB_PWD"

            # Push the Docker image to the registry
            docker push phogatone/nodejs:$IMAGETAG

workflows:
  version: 2
  nodejs-build-flow:
    jobs:
    - build:
        filters:
          branches:
            only:
            - main
